# Generated by Django 5.1.1 on 2025-02-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_picture',
        ),
        migrations.RemoveField(
            model_name='eventorganizer',
            name='profile_picture',
        ),
    ]
