# Generated by Django 5.1.1 on 2025-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_remove_event_event_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_profiles/'),
        ),
    ]
